name: "Rust Test"

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Cache dependencies"
        uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1
        with:
          key: ${{ inputs.target }}

      - name: "Run tests"
        run: cargo test --no-fail-fast
        env:
          RUST_BACKTRACE: full
