# Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses (https://spdx.org/licenses/)
allow-licenses:
  - Apache-2.0
  - MIT
  - PSF-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - MPL-2.0
  - Unlicense
  - ISC
