version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      callable-workflows:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "workflow-templates"
    schedule:
      interval: "monthly"
    groups:
      template-workflows:
        patterns:
          - "*"
