# Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses (https://spdx.org/licenses/)
allow-licenses:
  - Apache-2.0
  - MIT
  - PSF-2.0
  - LGPL-3.0
  - BSD-2-Clause
  - BSD-3-Clause
  - BSD-2-Clause AND BSD-3-Clause
  - MPL-2.0
  - Unlicense
  - ISC
  - (Apache-2.0 AND BSD-3-Clause) OR (Apache-2.0 AND MIT)
  - Python-2.0
  - Python-2.0.1
  - Apache-2.0 AND MIT
  - LGPL-2.0-only AND LGPL-2.1-or-later # astroid
  - BSD-2-Clause AND MIT
