name: "Python CI"

on:
  push:
    branches:
      - $default-branch
  pull_request:
  merge_group:

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@440166417b42442c6114aaa895094f0db7de9b78 # v15.2.0

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@440166417b42442c6114aaa895094f0db7de9b78 # v15.2.0
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  docs:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    uses: darbiadev/.github/.github/workflows/github-pages-python-sphinx.yaml@440166417b42442c6114aaa895094f0db7de9b78 # v15.2.0
