name: "Python CI"

on:
  push:
    branches:
      - $default-branch
  pull_request:
  merge_group:

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@35ec51819cd4cbfe7f93d24e3307ef24753a681a # v13.0.4

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@35ec51819cd4cbfe7f93d24e3307ef24753a681a # v13.0.4
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  docs:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    uses: darbiadev/.github/.github/workflows/github-pages-python-sphinx.yaml@35ec51819cd4cbfe7f93d24e3307ef24753a681a # v13.0.4
