name: "Rust CI"

on:
  push:
    branches:
      - $default-branch
  pull_request:
  merge_group:

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@12e07d61ed37c908baa73f8d5550281b3ed9cddd # v13.1.2

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@12e07d61ed37c908baa73f8d5550281b3ed9cddd # v13.1.2

  test:
    needs: clippy
    strategy:
      matrix:
        triple:
          - {
            os: "ubuntu-latest",
            target: "x86_64-unknown-linux-gnu",
          }
          - {
            os: "macOS-latest",
            target: "x86_64-apple-darwin",
          }
          - {
            os: "windows-latest",
            target: "x86_64-pc-windows-msvc",
          }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@12e07d61ed37c908baa73f8d5550281b3ed9cddd # v13.1.2
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}

  docs:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    uses: darbiadev/.github/.github/workflows/github-pages-rust-doc.yaml@12e07d61ed37c908baa73f8d5550281b3ed9cddd # v13.1.2
