name: "pre-commit autoupdate"

on:
  workflow_call:

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: "Run pre-commit autoupdate"
        run: |
          pip install pre-commit
          pre-commit autoupdate

      - name: "Create PR to update checks"
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
